from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Tuple

import torch


def _get_seed(cfg, default: int = 42) -> int:
    """Best-effort seed extraction.

    Supports cfg.seed.torch, cfg.seed.master, or a plain dict-like config.
    """
    for key in (("seed", "torch"), ("seed", "master")):
        cur = cfg
        ok = True
        for k in key:
            if hasattr(cur, k):
                cur = getattr(cur, k)
            elif isinstance(cur, dict) and k in cur:
                cur = cur[k]
            else:
                ok = False
                break
        if ok and isinstance(cur, int):
            return cur
    return default


def _normalize_ratios(ratios: Sequence[float]) -> List[float]:
    rs = [float(r) for r in ratios]
    s = sum(rs)
    if s <= 0:
        raise ValueError(f"Invalid split ratios (sum <= 0): {ratios}")
    return [r / s for r in rs]


def compute_split_lengths(total: int, ratios: Sequence[float]) -> List[int]:
    """Compute split lengths that sum exactly to total."""
    if total <= 0:
        raise ValueError(f"Invalid total: {total}")
    rs = _normalize_ratios(ratios)

    lengths = [int(total * r) for r in rs]
    # Fix rounding error by assigning remainder to the last split.
    remainder = total - sum(lengths)
    lengths[-1] += remainder

    # Guard against pathological rounding (e.g., tiny total).
    if any(l < 0 for l in lengths) or sum(lengths) != total:
        raise RuntimeError(f"Bad split lengths: total={total}, ratios={ratios}, lengths={lengths}")
    return lengths


def split_indices(total: int, ratios: Sequence[float], seed: int) -> List[torch.Tensor]:
    """Return a list of index tensors split according to ratios.

    Indices are generated by a deterministic random permutation controlled by seed.
    """
    lengths = compute_split_lengths(total, ratios)
    g = torch.Generator()
    g.manual_seed(int(seed))

    perm = torch.randperm(total, generator=g)
    out: List[torch.Tensor] = []
    offset = 0
    for n in lengths:
        out.append(perm[offset : offset + n])
        offset += n
    return out


@dataclass(frozen=True)
class TwoStageSplit:
    """Two-stage split used in this project.

    Stage 1: (aux, private_pool)  via r_aux
    Stage 2: private_pool -> (train, val) via train_val_split
    """

    aux: torch.Tensor
    train: torch.Tensor
    val: torch.Tensor


def two_stage_split_indices(
    total: int,
    r_aux: float,
    train_val_split: Sequence[float],
    seed: int,
) -> TwoStageSplit:
    if not (0.0 < float(r_aux) < 1.0):
        raise ValueError(f"r_aux must be in (0,1), got {r_aux}")

    aux_idx, priv_idx = split_indices(total, [r_aux, 1.0 - r_aux], seed=seed)
    # Stage 2: split priv into train/val with a different seed to avoid coupling.
    train_idx_rel, val_idx_rel = split_indices(len(priv_idx), train_val_split, seed=seed + 1)

    train_idx = priv_idx[train_idx_rel]
    val_idx = priv_idx[val_idx_rel]
    return TwoStageSplit(aux=aux_idx, train=train_idx, val=val_idx)


def get_default_train_val_split(cfg) -> Tuple[float, float]:
    tv = getattr(cfg.data, "train_val_split", None)
    if tv is None:
        return 0.9, 0.1
    if isinstance(tv, (list, tuple)) and len(tv) == 2:
        return float(tv[0]), float(tv[1])
    raise ValueError(f"cfg.data.train_val_split must be [train_ratio, val_ratio], got {tv}")


def get_default_r_aux(cfg, default: float = 0.2) -> float:
    # Priority: cfg.privacy.aux_dataset.r_aux (or ratio) -> cfg.data.r_aux -> default
    aux = getattr(getattr(cfg, "privacy", None), "aux_dataset", None)
    for k in ("r_aux", "ratio"):
        if aux is not None and hasattr(aux, k):
            v = getattr(aux, k)
            if v is not None:
                return float(v)

    if hasattr(cfg, "data") and hasattr(cfg.data, "r_aux"):
        v = getattr(cfg.data, "r_aux")
        if v is not None:
            return float(v)
    return float(default)


def get_split_seed(cfg, default: int = 42) -> int:
    return _get_seed(cfg, default=default)
